### ISSUE TITLE
A misprint?

### ISSUE THREAD

**Issue by aprokop** [ibaned/lambda_users_guide#1]
> If C++17 is enabled, KOKKOS_CLASS_LAMBDA will be defined to either `[=,*this] __host__ __device__` or `[=,*this]` depending on whether CUDA is enabled.

Should probably be

If C++17 is enabled, KOKKOS_CLASS_LAMBDA will be defined to either `[=,*this] __host__ __device__` or `[=,*this] __device__` depending on whether CUDA is enabled.

**Comment by aprokop** [comment]
@ibaned realized that you probably won't see this otherwise.

**Comment by ibaned** [comment]
@aprokop right ! Didn't see it until the mention.

I don't think its a misprint, although I can see the confusion when comparing to `KOKKOS_LAMBDA`.

I've attempted to make the text more clear in 5af1d00.
Let me know if it worked.

Thanks for reading this document !

**Comment by aprokop** [comment]
~No, my concern was missing `__device__` in the second clause. Should not it have it? Otherwise, how would it run on the device?~
Nevermind, just carefully reread it. I read it wrong in the first place too (instead of "if CUDA is enabled", I was reading if CUDA 8 is enabled... stupid me). Looks good (even the original version is fine), sorry.

And thank you for writing this doc! This was very useful, especially assembled in a single place. Nice place to reference for other people too.

**Comment by ibaned** [comment]
Yea, there is no such variant. I tried to further explain why in 06a086a.

It know it can be weird that I'm not answering you clearly in the comments, but I want the answer to be such that all future readers will see it too.
